### ISSUE TITLE
Getting non-existant supervisor child error when trying to start cluster

### ISSUE THREAD

**Issue by wittjosiah** [kyleaa/libcluster_ec2#18]
Trying to setup a small cluster based on ec2 tags. I've setup the libcluster config as such:
```
    topologies = [
      my_app: [
        strategy: ClusterEC2.Strategy.Tags,
        config: [
          ec2_tagname: "ex_cluster_id",
          ec2_tagvalue: ec2_tagvalue,
          app_prefix: "my_app",
          ip_type: :private
        ]
      ]
    ]

    children = [
      {Cluster.Supervisor, [topologies, [name: MyAppWeb.ClusterSupervisor]]},
      MyAppWeb.Endpoint
    ]

    opts = [strategy: :one_for_one, name: MyAppWeb.Supervisor]
    Supervisor.start_link(children, opts)
```

Unfortunately after building the release and running it on each node I'm getting the following error:
```
19:00:20.139 [info] Application my_app_web exited: exited in: MyAppWeb.Application.start(:normal, [])
    ** (EXIT) an exception was raised:
        ** (ArgumentError) The module Cluster.Supervisor was given as a child to a supervisor but it does not exist.
            (elixir) lib/supervisor.ex:629: Supervisor.init_child/1
            (elixir) lib/enum.ex:1327: Enum."-map/2-lists^map/1-0-"/2
            (elixir) lib/supervisor.ex:615: Supervisor.init/2
            (elixir) lib/supervisor.ex:564: Supervisor.start_link/2
            (kernel) application_master.erl:277: :application_master.start_it_old/4
{"Kernel pid terminated",application_controller,"{application_start_failure,my_app_web,{bad_return,{{'Elixir.MyAppWeb.Application',start,[normal,[]]},{'EXIT',{#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<\"The module Cluster.Supervisor was given as a child to a supervisor but it does not exist.\">>},[{'Elixir.Supervisor',init_child,1,[{file,\"lib/supervisor.ex\"},{line,629}]},{'Elixir.Enum','-map/2-lists^map/1-0-',2,[{file,\"lib/enum.ex\"},{line,1327}]},{'Elixir.Supervisor',init,2,[{file,\"lib/supervisor.ex\"},{line,615}]},{'Elixir.Supervisor',start_link,2,[{file,\"lib/supervisor.ex\"},{line,564}]},{application_master,start_it_old,4,[{file,\"application_master.erl\"},{line,277}]}]}}}}}"}
Kernel pid terminated (application_controller) ({application_start_failure,my_app_web,{bad_return,{{'Elixir.MyAppWeb.Application',start,[normal,[]]},{'EXIT',{#{'__exception__' => true,'__struct__' =>
```

I'm assuming this has something to do with how I've setup the EC2 tags strategy because when I use the gossip strategy locally it seems to work fine. Any insight you might have into the issue or possible misconfiguration is appreciated!

**Comment by kyleaa** [comment]
The error is saying that the module `Cluster.Supervisor` does not exist. This is provided by the `libcluster` package. It was added in libcluster 3.0, so make sure that your version defined in your application is high enough. This strategy should be compatible with both libcluster 2 or 3 based on community usage, but I haven't personally tested it on 3.

**Comment by wittjosiah** [comment]
@kyleaa ah that makes sense, I totally misread that error. I thought it was saying the child passed to `Cluster.Supervisor` didn't exist. This makes a lot more sense! I now suspect libcluster just isn't being properly included in the release as it is functioning fine locally using the Gossip strategy as I mentioned before.

Thanks for taking a look at this!
