### ISSUE TITLE
Error starting phoenix app

### ISSUE THREAD

**Issue by sonic182** [kyleaa/libcluster_ec2#25]
Any Idea what could be wrong here? I'm just upgrading erlang/elixir version from a app that works with prev version

```
-  ERLANG_VERSION="1:22.3.4-1"
-  ELIXIR_VERSION="1.10.4-1"
+  ERLANG_VERSION="1:23.2.3-1"
+  ELIXIR_VERSION="1.11.2-1"
```

```
14:36:25.581 [info]  Application xxx exited: XXX.Application.start(:normal, []) returned an error: shutdown: failed to start child: Cluster.Supervisor
    ** (EXIT) shutdown: failed to start child: :xxx        ** (EXIT) an exception was raised:            ** (ArgumentError) expected a keyword list, but an entry in the list is not a two-element tuple with an atom as its first element, got: {"content-type", "application/x-www-form-urlencoded"}                (elixir 1.11.2) lib/keyword.ex:475: Keyword.keys/1                (ex_aws 2.0.2) lib/ex_aws/auth.ex:110: ExAws.Auth.build_canonical_request/5                (ex_aws 2.0.2) lib/ex_aws/auth.ex:96: ExAws.Auth.signature/8
                (ex_aws 2.0.2) lib/ex_aws/auth.ex:87: ExAws.Auth.auth_header/7
                (ex_aws 2.0.2) lib/ex_aws/auth.ex:39: ExAws.Auth.headers/6
                (ex_aws 2.0.2) lib/ex_aws/request.ex:27: ExAws.Request.request_and_retry/7
                (ex_aws 2.0.2) lib/ex_aws/operation/query.ex:33: ExAws.Operation.ExAws.Operation.Query.perform/2
                (libcluster_ec2 0.6.0) lib/strategy/tags.ex:141: ClusterEC2.Strategy.Tags.get_nodes/1[os_mon] memory supervisor port (memsup): Erlang has closed[os_mon] cpu supervisor port (cpu_sup): Erlang has closed
```

**Comment by sonic182** [comment]
I fixed by updating ex_aws to 2.1
